BEGIN
	DECLARE V_ID INT; -- 活动ID
	DECLARE V_OPERATORID INT; -- 创建活动的操作者ID（这里实际是经销商ID）
	DECLARE v_panduan1 INT ;
	DECLARE v_panduan2 INT ;
	DECLARE v_fetch_ok BOOLEAN;

	-- 游标：活动操作类型 OPERTYPE = 3 的数据集合
	DECLARE T_ACTIVITY_C CURSOR FOR SELECT ID,OPERATORID FROM T_ACTIVITY WHERE OPERTYPE = 3 ORDER BY ID ASC;
	-- 判断退出循环游标标示
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_fetch_ok = TRUE; 	

	-- 开始业务处理
	OPEN T_ACTIVITY_C;
		T_ACTIVITY_LOOP:	LOOP FETCH T_ACTIVITY_C INTO V_ID,V_OPERATORID ;
			IF v_fetch_ok THEN 
				-- 退出循环游标
				LEAVE T_ACTIVITY_LOOP;
			ELSE    
			-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
				SET v_panduan1 = (SELECT count(ID) FROM T_ACTIVITY_SCOPE WHERE OPERTYPE = 3 AND AID = V_ID AND OPERID = V_OPERATORID ) ;
				SET v_panduan2 = (SELECT count(ID) FROM T_ACTIVITY_SCOPE WHERE OPERTYPE = 5 AND AID = V_ID AND OPERID = V_OPERATORID ) ;

				-- 更新同步目标
				UPDATE T_ACTIVITY SET SYNCOBJECT = '3,5,1,2' WHERE 1=1 AND ID = V_ID AND OPERTYPE = 3 AND (SYNCOBJECT IS NULL OR SYNCOBJECT = '');

				-- 业务逻辑处理 BEGIN
				IF v_panduan1 = 0 THEN 
				 INSERT INTO T_ACTIVITY_SCOPE (VERSON,OPERID,OPERTYPE,AID,ISALL,CDATE,UDATE) VALUES (0,V_OPERATORID,3,V_ID,0,NOW(),NOW());
				END IF ;

				IF v_panduan2 = 0 THEN 
				 INSERT INTO T_ACTIVITY_SCOPE (VERSON,OPERID,OPERTYPE,AID,ISALL,CDATE,UDATE) VALUES (0,V_OPERATORID,5,V_ID,0,NOW(),NOW());
				END IF ;
				-- 业务逻辑处理 END
				SET v_fetch_ok = 0;
			END IF;
	END LOOP T_ACTIVITY_LOOP;
	CLOSE T_ACTIVITY_C;
	# 结束
END