BEGIN
	DECLARE V_ID INT; #促销ID
	DECLARE V_DEALERID INT; -- 创建活动的操作者ID（这里实际是经销商ID）
	DECLARE v_panduan1 INT ; 
	DECLARE v_panduan2 INT ;
	DECLARE v_fetch_ok BOOLEAN;

	-- 游标：促销数据集合
	DECLARE T_PROMOTION_C CURSOR FOR SELECT ID,DEALERID FROM T_PROMOTION ORDER BY ID ASC;
	-- 判断退出循环游标标示
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_fetch_ok = TRUE; 	
	
	-- 开始业务处理
	OPEN T_PROMOTION_C;
	 T_PROMOTION_LOOP:	LOOP FETCH T_PROMOTION_C INTO V_ID,V_DEALERID ;
		IF v_fetch_ok THEN 
			-- 退出循环游标
			LEAVE T_PROMOTION_LOOP;
		ELSE    
			-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
			SET v_panduan1 = (SELECT COUNT(ID) FROM T_PROMOTION_SCOPE WHERE OPERTYPE = 3 AND PID = V_ID AND OPERID = V_DEALERID);
			SET v_panduan2 = (SELECT COUNT(ID) FROM T_PROMOTION_SCOPE WHERE OPERTYPE = 5 AND PID = V_ID AND OPERID = V_DEALERID);

			-- 更新同步目标
			UPDATE T_PROMOTION SET OPERID = DEALERID,OPERTYPE = 3,SYNCOBJECT = '3,5,1,2',ADMINCHECKSTATE = 1,AREACHECKSTATE = 1 WHERE ID = V_ID AND (SYNCOBJECT IS NULL OR SYNCOBJECT = '');

			-- 业务逻辑处理
			IF v_panduan1 = 0  THEN 
				INSERT INTO T_PROMOTION_SCOPE (VERSON,OPERID,OPERTYPE,PID,ISALL,CDATE,UDATE) VALUES (0,V_DEALERID,3,V_ID,0,NOW(),NOW());
			END IF ;

			IF v_panduan2 = 0 THEN 
				INSERT INTO T_PROMOTION_SCOPE (VERSON,OPERID,OPERTYPE,PID,ISALL,CDATE,UDATE) VALUES (0,V_DEALERID,5,V_ID,0,NOW(),NOW());
			END IF ;

			SET v_fetch_ok = 0;
		END IF;
	END LOOP T_PROMOTION_LOOP;
	CLOSE T_PROMOTION_C;
	# 结束
END